export enum MakeNewChannel {
    MAKE_NEW_CHANNEL_LOADING = "MAKE_NEW_CHANNEL_LOADING",
    MAKE_NEW_CHANNEL_SUCCESS = "MAKE_NEW_CHANNEL_SUCCESS",
    MAKE_NEW_CHANNEL_ERROR = "MAKE_NEW_CHANNEL_ERROR"
}
