export enum SearchUserType {
    SEARCH_LOADING = "SEARCH_LOADING",
    SEARCH_SUCCESS = "SEARCH_SUCCESS",
    SEARCH_ERROR = "SEARCH_ERROR"
}


export enum ChatsType {
    CHATS_LOADING = "CHATS_LOADING",
    CHATS_ADD_MESSAGE = "CHATS_ADD_MESSAGE",
    CHATS_GET_THREADS = "CHATS_GET_THREADS",
    CHATS_PIN_MESSAGE = "CHATS_PIN_MESSAGE",
    CHATS_SEEN_MESSAGE = "CHATS_SEEN_MESSAGE",
    CHATS_REMOVE_MESSAGE = "CHATS_REMOVE_MESSAGE",
    CHATS_LOAD_MORE_MESSAGES = "CHATS_LOAD_MORE_MESSAGES",
    CHATS_ADD_TO_GROUP = "CHATS_ADD_TO_GROUP",
    CHATS_GET_GROUP_MEMBERS = "CHATS_GET_GROUP_MEMBERS",
    CHATS_ERROR = "CHATS_ERROR"
}

export enum OnlineUsersType {
    ADD_ONLINE_USERS = "ADD_ONLINE_USERS",
    REMOVE_OFFLINE_USERS = "REMOVE_OFFLINE_USERS",
}
