export enum SearchUserType {
    SEARCH_LOADING = "SEARCH_LOADING",
    SEARCH_SUCCESS = "SEARCH_SUCCESS",
    SEARCH_ERROR = "SEARCH_ERROR"
}


export enum ChatsType {
    CHATS_LOADING = "CHATS_LOADING",
    CHATS_ADD_MESSAGE = "CHATS_ADD_MESSAGE",
    CHATS_GET_THREADS = "CHATS_GET_THREADS",
    CHATS_PIN_MESSAGE = "CHATS_PIN_MESSAGE",
    CHATS_ERROR = "CHATS_ERROR"
}
